feat(Sharing): render image to sharing
Vincenius/workout-lol pull request #47
Opened 2023-07-11 10:43 UTC by ngthuongdoan

#23 
@Vincenius I'm using html-to-image and it's working fine on mobile native share. But on desktop maybe we'll need a extra modal for that

2023-07-11 10:44 UTC, ngthuongdoan commented
![image](https://github.com/Vincenius/workout-lol/assets/45509523/f1f77091-7c2f-4034-a19b-c8358c823962)
Currently the post will look like this, you can help me redesign it

2023-07-12 05:55 UTC, Vincenius commented
I will look into this tomorrow or Friday :)

2023-07-13 05:04 UTC, Vincenius requested changes
Looks good in general! Thanks!
It needs some minor changes related to the dark mode and we need to replace canShare()

2023-07-13 05:04 UTC, Vincenius commented on components/Workout.js
> +						variant="white"
Let's use variant="outline" here to make it also look good on dark mode :)

Also add mt="md" to add some margin top

2023-07-24 03:04 UTC, ngthuongdoan commented on components/SharingModal/index.js
> +			if (!navigator?.canShare(data)) {
@Vincenius I read that post for doing this. But as I mentioned before, we need a sharing option for desktop version and which devices not supported. I think this is native Web API so third-party library cannot do it as well
Image for references:
<img width="537" alt="image" src="https://github.com/Vincenius/workout-lol/assets/45509523/cac702ab-83a6-48fa-8b49-2845976984e9">

2026-04-09 03:51 UTC, closed without merging